"""Frozen OpenAPI URL-key baseline at M6 (`a0131456`).

Single source for the layer-④ "no-shrink" guard (@架构 seq3057): later add-only
batches (P3-5, …) may ADD keys but must never remove any of these 144 keys.

Source: `docs/openapi.json` at M6, blob
`90c594fb3acc973f1822f0189c3ac51268b10693` (`len(paths) == 144`).
Do NOT regenerate this from the live app — it is a FROZEN pre-P3-5 snapshot; if it
were recomputed from the current build the net-zero-substitution hole would reopen.
"""

from __future__ import annotations

M6_P3_4_KEYS = (
    "/api/v1/approvals",
    "/api/v1/approvals/rules",
    "/api/v1/approvals/rules/{rule_id}",
    "/api/v1/approvals/{approval_id}",
    "/api/v1/approvals/{approval_id}/approve",
    "/api/v1/approvals/{approval_id}/cancel",
    "/api/v1/approvals/{approval_id}/reject",
    "/api/v1/assets/cmdb/impact",
    "/api/v1/assets/cmdb/topology",
    "/api/v1/assets/credentials",
    "/api/v1/assets/credentials/{cred_id}",
    "/api/v1/assets/groups",
    "/api/v1/assets/groups/tree",
    "/api/v1/assets/groups/{group_id}",
    "/api/v1/assets/hosts",
    "/api/v1/assets/hosts/export",
    "/api/v1/assets/hosts/import",
    "/api/v1/assets/hosts/stats",
    "/api/v1/assets/hosts/{host_id}",
    "/api/v1/assets/hosts/{host_id}/conn",
    "/api/v1/assets/hosts/{host_id}/connector",
    "/api/v1/assets/hosts/{host_id}/executors",
    "/api/v1/assets/options",
    "/api/v1/assets/relations",
    "/api/v1/assets/relations/{relation_id}",
    "/api/v1/auth/ldap/login",
    "/api/v1/auth/login",
    "/api/v1/auth/logout",
    "/api/v1/auth/me",
    "/api/v1/auth/oauth/{provider}/callback",
    "/api/v1/auth/oauth/{provider}/login",
    "/api/v1/auth/password",
    "/api/v1/auth/providers",
    "/api/v1/auth/providers/{provider_id}",
    "/api/v1/auth/providers/{provider_id}/status",
    "/api/v1/auth/providers/{provider_id}/test",
    "/api/v1/auth/refresh",
    "/api/v1/dashboard/recent-approvals",
    "/api/v1/dashboard/recent-tasks",
    "/api/v1/dashboard/stats",
    "/api/v1/dashboard/task-trend",
    "/api/v1/exec/tasks",
    "/api/v1/exec/tasks/{task_id}",
    "/api/v1/exec/tasks/{task_id}/hosts/{task_host_id}/logs",
    "/api/v1/exec/tasks/{task_id}/hosts/{task_host_id}/ws-token",
    "/api/v1/exec/tasks/{task_id}/retry",
    "/api/v1/exec/tasks/{task_id}/stats",
    "/api/v1/exec/tasks/{task_id}/stop",
    "/api/v1/kb/articles",
    "/api/v1/kb/articles/{article_id}",
    "/api/v1/kb/articles/{article_id}/rollback",
    "/api/v1/kb/articles/{article_id}/versions",
    "/api/v1/kb/articles/{article_id}/versions/{version}",
    "/api/v1/kb/categories",
    "/api/v1/kb/categories/{category_id}",
    "/api/v1/kb/search",
    "/api/v1/monitor/adapters",
    "/api/v1/monitor/adapters/{adapter_id}",
    "/api/v1/monitor/adapters/{adapter_id}/status",
    "/api/v1/monitor/adapters/{adapter_id}/test",
    "/api/v1/monitor/alerts",
    "/api/v1/monitor/alerts/{alert_id}",
    "/api/v1/monitor/alerts/{alert_id}/acknowledge",
    "/api/v1/monitor/alerts/{alert_id}/events",
    "/api/v1/monitor/alerts/{alert_id}/resolve",
    "/api/v1/monitor/events",
    "/api/v1/monitor/events/{event_id}",
    "/api/v1/monitor/ingest/{adapter_id}",
    "/api/v1/monitor/metrics",
    "/api/v1/monitor/metrics/current",
    "/api/v1/monitor/rules",
    "/api/v1/monitor/rules/{rule_id}",
    "/api/v1/monitor/rules/{rule_id}/status",
    "/api/v1/monitor/rules/{rule_id}/test",
    "/api/v1/monitor/ws-token",
    "/api/v1/notify/channels",
    "/api/v1/notify/channels/{channel_id}",
    "/api/v1/notify/channels/{channel_id}/status",
    "/api/v1/notify/channels/{channel_id}/test",
    "/api/v1/notify/records",
    "/api/v1/notify/records/{record_id}/resend",
    "/api/v1/schedules",
    "/api/v1/schedules/{schedule_id}",
    "/api/v1/schedules/{schedule_id}/run-now",
    "/api/v1/schedules/{schedule_id}/runs",
    "/api/v1/schedules/{schedule_id}/runs/{run_id}/retry",
    "/api/v1/schedules/{schedule_id}/status",
    "/api/v1/scripts",
    "/api/v1/scripts/{script_id}",
    "/api/v1/scripts/{script_id}/rollback",
    "/api/v1/scripts/{script_id}/test",
    "/api/v1/scripts/{script_id}/versions",
    "/api/v1/scripts/{script_id}/versions/{version}",
    "/api/v1/system/audit-logs",
    "/api/v1/system/audit-logs/export",
    "/api/v1/system/audit-logs/{log_id}",
    "/api/v1/system/permissions",
    "/api/v1/system/roles",
    "/api/v1/system/roles/{role_id}",
    "/api/v1/system/roles/{role_id}/groups",
    "/api/v1/system/roles/{role_id}/permissions",
    "/api/v1/system/users",
    "/api/v1/system/users/{user_id}",
    "/api/v1/system/users/{user_id}/password",
    "/api/v1/system/users/{user_id}/roles",
    "/api/v1/system/users/{user_id}/status",
    "/api/v1/terminals",
    "/api/v1/terminals/{session_id}",
    "/api/v1/terminals/{session_id}/close",
    "/api/v1/terminals/{session_id}/recording",
    "/api/v1/terminals/{session_id}/token",
    "/api/v1/tickets",
    "/api/v1/tickets/{ticket_id}",
    "/api/v1/tickets/{ticket_id}/accept",
    "/api/v1/tickets/{ticket_id}/assign",
    "/api/v1/tickets/{ticket_id}/attachments",
    "/api/v1/tickets/{ticket_id}/cancel",
    "/api/v1/tickets/{ticket_id}/close",
    "/api/v1/tickets/{ticket_id}/comments",
    "/api/v1/tickets/{ticket_id}/done",
    "/api/v1/tickets/{ticket_id}/process",
    "/api/v1/tickets/{ticket_id}/refs",
    "/api/v1/tickets/{ticket_id}/reopen",
    "/api/v1/transfer/packages",
    "/api/v1/transfer/packages/{package_id}",
    "/api/v1/transfer/tasks",
    "/api/v1/transfer/tasks/mine",
    "/api/v1/transfer/tasks/{task_id}",
    "/api/v1/transfer/tasks/{task_id}/hosts/{transfer_host_id}/logs",
    "/api/v1/transfer/tasks/{task_id}/hosts/{transfer_host_id}/retry",
    "/api/v1/transfer/tasks/{task_id}/hosts/{transfer_host_id}/ws-token",
    "/api/v1/transfer/tasks/{task_id}/stats",
    "/api/v1/transfer/tasks/{task_id}/stop",
    "/api/v1/workflow-runs",
    "/api/v1/workflow-runs/{run_id}",
    "/api/v1/workflow-runs/{run_id}/callback/{node_key}",
    "/api/v1/workflow-runs/{run_id}/cancel",
    "/api/v1/workflow-runs/{run_id}/retry",
    "/api/v1/workflow-runs/{run_id}/ws-token",
    "/api/v1/workflows",
    "/api/v1/workflows/{workflow_id}",
    "/api/v1/workflows/{workflow_id}/rollback",
    "/api/v1/workflows/{workflow_id}/run",
    "/api/v1/workflows/{workflow_id}/versions",
)

if len(M6_P3_4_KEYS) != 144:  # pragma: no cover — freeze guard for the M6 baseline
    raise RuntimeError(f"M6 openapi baseline must have exactly 144 keys; got {len(M6_P3_4_KEYS)}")
